sonar.projectKey=neoflex_creditbank
sonar.organization=neoflex

sonar.modules=deal,gateway,statement,calculator,dossier,config-server,eureka-server

sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml