sonar.projectKey=Win122333_neoflex-creditbank
sonar.organization=win122333

sonar.modules=deal,gateway,statement,calculator,dossier,config-server,eureka-server

sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml