<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>neoflex.chulkov</groupId>
    <artifactId>dossier</artifactId>
    <version>1.0-SNAPSHOT</version>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.11</version>
    </parent>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <lombok-version>1.18.42</lombok-version>
        <springdoc-version>2.8.5</springdoc-version>
        <mapstruct-version>1.6.3</mapstruct-version>
        <wiremock-version>3.3.1</wiremock-version>
        <openapi-generator-version>7.9.0</openapi-generator-version>
        <jackson-databind-version>0.2.6</jackson-databind-version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok-version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>${springdoc-version}</version>
        </dependency>


        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
            <scope>compile</scope>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>org.openapitools</groupId>-->
<!--            <artifactId>jackson-databind-nullable</artifactId>-->
<!--            <version>${jackson-databind-version}</version>-->
<!--        </dependency>-->
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-mail</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>
    </dependencies>
    <build>
        <plugins>
<!--            <plugin>-->
<!--                <groupId>org.codehaus.mojo</groupId>-->
<!--                <artifactId>build-helper-maven-plugin</artifactId>-->
<!--                <version>3.5.0</version>-->
<!--                <executions>-->
<!--                    <execution>-->
<!--                        <id>add-source</id>-->
<!--                        <phase>generate-sources</phase>-->
<!--                        <goals>-->
<!--                            <goal>add-source</goal>-->
<!--                        </goals>-->
<!--                        <configuration>-->
<!--                            <sources>-->
<!--                                <source>${project.build.directory}/generated-sources/openapi/src/main/java</source>-->
<!--                            </sources>-->
<!--                        </configuration>-->
<!--                    </execution>-->
<!--                </executions>-->
<!--            </plugin>-->
<!--            <plugin>-->
<!--                <groupId>org.openapitools</groupId>-->
<!--                <artifactId>openapi-generator-maven-plugin</artifactId>-->
<!--                <version>7.9.0</version>-->
<!--                <executions>-->
<!--                    <execution>-->
<!--                        <goals>-->
<!--                            <goal>generate</goal>-->
<!--                        </goals>-->
<!--                        <configuration>-->
<!--                            <inputSpec>${project.basedir}/src/main/resources/api-docs.yaml</inputSpec>-->
<!--                            <generatorName>spring</generatorName>-->
<!--                            <apiPackage>neoflex.chulkov.api</apiPackage>-->
<!--                            <modelPackage>neoflex.chulkov.dto</modelPackage>-->
<!--                            <invokerPackage>neoflex.chulkov</invokerPackage>-->
<!--                            <supportingFilesToGenerate>ApiUtil.java</supportingFilesToGenerate>-->
<!--                            <configOptions>-->
<!--                                <interfaceOnly>false</interfaceOnly>-->
<!--                                <delegatePattern>true</delegatePattern>-->
<!--                                <useSpringBoot3>true</useSpringBoot3>-->
<!--                                <useJakartaEe>true</useJakartaEe>-->
<!--                                <serializableModel>true</serializableModel>-->
<!--                            </configOptions>-->

<!--&lt;!&ndash;                            <typeMappings>&ndash;&gt;-->
<!--&lt;!&ndash;                                <typeMapping>ApplicationStatus=neoflex.chulkov.dto.enums.ApplicationStatus</typeMapping>&ndash;&gt;-->
<!--&lt;!&ndash;                                <typeMapping>ChangeType=neoflex.chulkov.dto.enums.ChangeType</typeMapping>&ndash;&gt;-->
<!--&lt;!&ndash;                                <typeMapping>Gender=neoflex.chulkov.dto.enums.Gender</typeMapping>&ndash;&gt;-->
<!--&lt;!&ndash;                                <typeMapping>MaritalStatus=neoflex.chulkov.dto.enums.MaritalStatus</typeMapping>&ndash;&gt;-->
<!--&lt;!&ndash;                            </typeMappings>&ndash;&gt;-->

<!--&lt;!&ndash;                            <importMappings>&ndash;&gt;-->
<!--&lt;!&ndash;                                <importMapping>ApplicationStatus=neoflex.chulkov.dto.enums.ApplicationStatus</importMapping>&ndash;&gt;-->
<!--&lt;!&ndash;                                <importMapping>ChangeType=neoflex.chulkov.dto.enums.ChangeType</importMapping>&ndash;&gt;-->
<!--&lt;!&ndash;                                <importMapping>Gender=neoflex.chulkov.dto.enums.Gender</importMapping>&ndash;&gt;-->
<!--&lt;!&ndash;                                <importMapping>MaritalStatus=neoflex.chulkov.dto.enums.MaritalStatus</importMapping>&ndash;&gt;-->
<!--&lt;!&ndash;                            </importMappings>&ndash;&gt;-->
<!--                        </configuration>-->
<!--                    </execution>-->
<!--                </executions>-->
<!--            </plugin>-->
<!--            <plugin>-->
<!--                <groupId>org.openapitools</groupId>-->
<!--                <artifactId>openapi-generator-maven-plugin</artifactId>-->
<!--                <version>${openapi-generator-version}</version>-->
<!--                <executions>-->
<!--                    <execution>-->
<!--                        <goals>-->
<!--                            <goal>generate</goal>-->
<!--                        </goals>-->
<!--                        <configuration>-->
<!--                            <inputSpec>${project.basedir}/src/main/resources/api-docs.yaml</inputSpec>-->
<!--                            <generatorName>spring</generatorName>-->
<!--                            <apiPackage>neoflex.chulkov.api</apiPackage>-->
<!--                            <modelPackage>neoflex.chulkov.dto</modelPackage>-->
<!--                            <invokerPackage>neoflex.chulkov</invokerPackage>-->
<!--                            <configOptions>-->
<!--                                <interfaceOnly>false</interfaceOnly>-->
<!--                                <delegatePattern>true</delegatePattern>-->
<!--                                <useSpringBoot3>true</useSpringBoot3>-->
<!--                                <useJakartaEe>true</useJakartaEe>-->
<!--                                <serializableModel>true</serializableModel>-->
<!--                            </configOptions>-->
<!--                        </configuration>-->
<!--                    </execution>-->
<!--                </executions>-->
<!--            </plugin>-->

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok-version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>0.2.0</version>
                        </path>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct-version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>