dossier:
  kafka:
    bootstrap: localhost:29092,localhost:39092,localhost:49092
spring:
  mail:
    port: 587
    username: ${MAIL_LOGIN}
    password: ${MAIL_PASSWORD}
    host: smtp.mail.ru
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true