server:
  port: 8084
dossier:
  kafka:
    bootstrap: localhost:29092,localhost:39092,localhost:49092
    consumer:
      properties:
        spring.json.use.type.headers: false
    topic:
      finish-registration: "finish-registration"
      create-documents: "create-documents"
      send-documents: "send-documents"
      send-ses: "send-ses"
      credit-issued: "credit-issued"
      statement-denied: "statement-denied"
spring:
  application:
    name: dossier
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus