dossier:
  kafka:
    bootstrap: localhost:29092,localhost:39092,localhost:49092
spring:
  mail:
    port: 2525
    username: a7f7578095d0e3
    password: c87921bee36855
    host: sandbox.smtp.mailtrap.io
    properties:
      mail:
        smth:
          auth: true
        smtp:
          starttls:
            enable: true